### ISSUE TITLE
Sort allow-plugins alphabetically

### ISSUE THREAD

**Issue by simPod** [localheinz/composer-normalize#860]
I wonder where the new `allow-plugins` composer.json section could be sorted alphabetically?

**Comment by localheinz** [comment]
@simPod 

I have disabled the sorting in https://github.com/ergebnis/json-normalizer/pull/590 because I believe this could break the configuration for people doing something like this:

```json
{
    "config": {
        "allow-plugins": {
            "my-organization/foo": false,
            "my-organization/*": true
        }
    }
}
```

When `config.allow-plugins` would be automatically sorted to

```json
{
    "config": {
        "allow-plugins": {
            "my-organization/*": true,
            "my-organization/foo": false
        }
    }
}
```

then `my-organization/foo` would be allowed, while it was actually configured with the intention to be disallowed.

For reference, see https://github.com/composer/composer/blob/2.2.3/src/Composer/Plugin/PluginManager.php#L696-L700.

What do you think?

**Comment by simPod** [comment]
I see, did not come up with such use-case. I guess that makes sense then. Thanks!

**Comment by localheinz** [comment]
Thank you, @simPod!
